/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Com.Sport.QuanLy;

import Com.Sport.Dao.HoaDonDao;
import Com.Sport.Dao.HoadonchitietDao;
import Com.Sport.Dao.SanPhamDao;
import Com.Sport.Entity.HoaDon;
import Com.Sport.Entity.HoaDonChiTiet;
import Com.Sport.Entity.KhachHang;
import Com.Sport.Entity.SanPham;
import Com.Sport.ultils.Auth;
import Com.Sport.ultils.MsgBox;
import Com.Sport.ultils.XDate;
import Com.Sport.ultils.XImage;
import java.io.File;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.PropertyConfigurator;

/**
 *
 * @author ADMIN
 */
public class HoaDonJdialog1 extends javax.swing.JDialog {
    List<SanPham> listsp = new ArrayList<>();
    private Double tongtien = 0.0;
    JFileChooser filechoose = new JFileChooser();

    /**
     * Creates new form hoadon1
     */
    public HoaDonJdialog1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        hoadon = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtmaHD = new javax.swing.JTextField();
        txtMaKh = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblhoadon = new javax.swing.JTable();
        datengaylap = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txttensp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtsoluong1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdongia1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblsanpham = new javax.swing.JTable();
        btnXoa3 = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnbrep = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        btntang = new javax.swing.JButton();
        btngiam = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txttongtienn = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtmasp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtthanhtien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblhoadonchitiet = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnMoi2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        btnSua2 = new javax.swing.JButton();
        btnThem2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtmahdct = new javax.swing.JTextField();
        txtMaHD1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btnFirst1 = new javax.swing.JButton();
        btnbrep1 = new javax.swing.JButton();
        btnNext1 = new javax.swing.JButton();
        btnLast1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lblhoadon1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel17.setText("Mã Hóa Đơn");

        jLabel18.setText("MaKH");

        txtmaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaHDActionPerformed(evt);
            }
        });

        jLabel19.setText("MaNV");

        jLabel20.setText("Ngay Lap");

        lblhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "tên sản phẩm", "Mã Khách Hàng", "Ngày Lập", "đơn giá", "số lượng", "tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhoadonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lblhoadon);

        datengaylap.setDateFormatString("dd-MM-yyyy");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel25.setText("Tên Sản Phẩm");

        jLabel28.setText("Số Lượng");

        txtsoluong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluong1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Giá");

        txtdongia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdongia1ActionPerformed(evt);
            }
        });

        lblsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên Sản phẩm", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lblsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsanphamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lblsanpham);

        btnXoa3.setText("Tìm");
        btnXoa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa3ActionPerformed(evt);
            }
        });

        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnbrep.setText("|<");
        btnbrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrepActionPerformed(evt);
            }
        });

        btnNext.setText(">|");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">>");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/Sport/Icon/Accept.png"))); // NOI18N
        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btntang.setText("+");
        btntang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntangActionPerformed(evt);
            }
        });

        btngiam.setText("-");
        btngiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(btngiam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtsoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btntang)))))
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtdongia1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem1)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnFirst)
                .addGap(30, 30, 30)
                .addComponent(btnbrep)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addGap(18, 18, 18)
                .addComponent(btnLast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoa3)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtsoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntang)
                    .addComponent(btngiam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdongia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnThem1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnbrep)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel26.setText("Tổng Tiền");

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/Sport/Icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/Sport/Icon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/Sport/Icon/Add.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jButton1.setText("Lịch sử hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hoadonLayout = new javax.swing.GroupLayout(hoadon);
        hoadon.setLayout(hoadonLayout);
        hoadonLayout.setHorizontalGroup(
            hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoadonLayout.createSequentialGroup()
                .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(hoadonLayout.createSequentialGroup()
                            .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(hoadonLayout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(hoadonLayout.createSequentialGroup()
                                    .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txttongtienn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(hoadonLayout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(datengaylap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(hoadonLayout.createSequentialGroup()
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(hoadonLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(hoadonLayout.createSequentialGroup()
                                    .addComponent(btnXoa)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSua)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMoi)))))
                    .addGroup(hoadonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        hoadonLayout.setVerticalGroup(
            hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoadonLayout.createSequentialGroup()
                .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hoadonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoadonLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(hoadonLayout.createSequentialGroup()
                                .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19)
                                    .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hoadonLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoadonLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(datengaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttongtienn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(28, 28, 28)
                        .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnMoi)
                            .addComponent(btnSua))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hóa Đơn", hoadon);

        jLabel9.setText("Chức Năng");

        lblhoadonchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn chi tiết", "Mã hóa đơn", "Mã Sản Phẩm", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lblhoadonchitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhoadonchitietMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lblhoadonchitiet);

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnMoi2.setText("Mới");
        btnMoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoi2ActionPerformed(evt);
            }
        });

        btnXoa2.setText("Xóa");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });

        btnSua2.setText("Sửa");
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua2ActionPerformed(evt);
            }
        });

        btnThem2.setText("Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem2)
                    .addComponent(btnSua2))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMoi2)
                    .addComponent(btnXoa2))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem2)
                    .addComponent(btnXoa2))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi2)
                    .addComponent(btnSua2))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel14.setText("Thành Tiền");

        jLabel10.setText("Mã Sản Phẩm");

        jLabel22.setText("Ma HDCT");

        jLabel23.setText("Mã Hóa Đơn");

        btnFirst1.setText("<<");
        btnFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst1ActionPerformed(evt);
            }
        });

        btnbrep1.setText("|<");
        btnbrep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrep1ActionPerformed(evt);
            }
        });

        btnNext1.setText(">|");
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        btnLast1.setText(">>");
        btnLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtmahdct, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmasp, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtthanhtien))))
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel9)
                        .addGap(229, 229, 229)
                        .addComponent(btnFirst1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbrep1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLast1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtmahdct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaHD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbrep1)
                            .addComponent(btnFirst1)
                            .addComponent(btnNext1)
                            .addComponent(btnLast1))
                        .addGap(3, 3, 3)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hóa Đơn Chi Tiết", jPanel2);

        lblhoadon1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Nhân Viên", "Mã Khách Hàng", "Ngày Lập", "đơn giá", "số lượng", "tổng tiền", "tên sản phẩm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lblhoadon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhoadon1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lblhoadon1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hóa đơn vừa thêm", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void lblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseClicked
        if (evt.getClickCount() == 2) {
            this.row = lblhoadon.getSelectedRow();
            this.edit();
            check();
        }
    }//GEN-LAST:event_lblhoadonMouseClicked

    private void txtmaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaHDActionPerformed

    private void txtsoluong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluong1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluong1ActionPerformed

    private void txtdongia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdongia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdongia1ActionPerformed

    private void lblsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsanphamMouseClicked

    }//GEN-LAST:event_lblsanphamMouseClicked

    private void btnXoa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa3ActionPerformed
        timKiem();
    }//GEN-LAST:event_btnXoa3ActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnbrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrepActionPerformed
        prev();
    }//GEN-LAST:event_btnbrepActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        insert();
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast1ActionPerformed
        this.last1();
    }//GEN-LAST:event_btnLast1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        this.next1();
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnbrep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrep1ActionPerformed
        this.prev1();
    }//GEN-LAST:event_btnbrep1ActionPerformed

    private void btnFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst1ActionPerformed
        this.first1();
    }//GEN-LAST:event_btnFirst1ActionPerformed

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        insert1();
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
        update1();
    }//GEN-LAST:event_btnSua2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        delete1();
    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void btnMoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoi2ActionPerformed
        clearForm1();
    }//GEN-LAST:event_btnMoi2ActionPerformed

    private void lblhoadonchitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonchitietMouseClicked
        if (evt.getClickCount() == 2) {
            this.row = lblhoadonchitiet.getSelectedRow();
            this.edit1();
            check();
        }
    }//GEN-LAST:event_lblhoadonchitietMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showMyJDialog();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblhoadon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblhoadon1MouseClicked

    private void btntangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntangActionPerformed
        JTextField txtsoluong1 = this.txtsoluong1;
        int value = Integer.parseInt(txtsoluong1.getText());
        value++;
        txtsoluong1.setText(String.valueOf(value));

    }//GEN-LAST:event_btntangActionPerformed

    private void btngiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiamActionPerformed
        JTextField txtsoluong1 = this.txtsoluong1;
         
        int value = Integer.parseInt(txtsoluong1.getText());
        if (value > 0) {
            value--;
            txtsoluong1.setText(String.valueOf(value));
        }
    }//GEN-LAST:event_btngiamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonJdialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonJdialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonJdialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonJdialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoaDonJdialog1 dialog = new HoaDonJdialog1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnFirst1;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLast1;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnMoi2;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JButton btnXoa3;
    private javax.swing.JButton btnbrep;
    private javax.swing.JButton btnbrep1;
    private javax.swing.JButton btngiam;
    private javax.swing.JButton btntang;
    private com.toedter.calendar.JDateChooser datengaylap;
    private javax.swing.JPanel hoadon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable lblhoadon;
    private javax.swing.JTable lblhoadon1;
    private javax.swing.JTable lblhoadonchitiet;
    private javax.swing.JTable lblsanpham;
    private javax.swing.JTextField txtMaHD1;
    private javax.swing.JTextField txtMaKh;
    private javax.swing.JTextField txtdongia1;
    private javax.swing.JTextField txtmaHD;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JTextField txtmahdct;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txtsoluong1;
    private javax.swing.JTextField txttensp;
    private javax.swing.JTextField txtthanhtien;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttongtienn;
    // End of variables declaration//GEN-END:variables

    HoaDonDao dao = new HoaDonDao();
    SanPhamDao spdao = new SanPhamDao();
    HoadonchitietDao dao1 = new HoadonchitietDao();
    int row = -1;

    HoaDonChiTiet hdtc = new HoaDonChiTiet();
//    double tongtien = hdtc.getThanhTien();

    private void init() {
        PropertyConfigurator.configure("\\DuAn1\\src\\Com\\Sport\\Log\\log4jj.properties");
        setLocationRelativeTo(null);
        setIconImage(XImage.getAppIcon());
        setTitle("Quản Lý Hóa Đơn");
        this.filltableChiTietHoaDon();
        // this.filltableHoaDon();
        this.filltablesanpham();
        //this.filltableHoaDonthem();
        this.row = -1;
        this.updateStatus();
        this.updateStatus1();
        check();
        txttongtienn.setText("0.0");
        txttongtienn.setEnabled(false);

        //txtmaNV.setText(Auth.user.getMaNV());
        txtsoluong1.setText("0");
        txtsoluong1.setHorizontalAlignment(SwingConstants.CENTER);
    }

    void check() {
        if (Auth.isManager()) {
            btnXoa.setEnabled(true);
            btnXoa.setToolTipText(null);
        } else {
            btnXoa.setEnabled(false);
            btnXoa.setToolTipText(null);
        }

    }

    public void filltableHoaDon() {

        DefaultTableModel model = (DefaultTableModel) lblhoadon.getModel();

        model.setRowCount(0);
        try {
            List<HoaDon> list = dao.selectAll();
            for (HoaDon hd : list) {
                double thanhtien = hd.getSoluong() * hd.getDongia();
                Object[] row = {
                    hd.getMaHD(),
                    hd.getMaNV(),
                    hd.getMaKH(),
                    hd.getNgayLap(),
                    hd.getDongia(),
                    hd.getSoluong(),
                    thanhtien,
                    hd.getTensp()

                };

                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!" + e.getMessage());
        }
    }

    public void filltableHoaDonthem() {

        DefaultTableModel model = (DefaultTableModel) lblhoadon1.getModel();

        model.setRowCount(0);
        try {
            List<HoaDon> list = dao.selectAll();
            for (HoaDon hd : list) {
                double thanhtien = hd.getSoluong() * hd.getDongia();
                Object[] row = {
                    hd.getMaHD(),
                    hd.getMaNV(),
                    hd.getMaKH(),
                    hd.getNgayLap(),
                    hd.getDongia(),
                    hd.getSoluong(),
                    thanhtien,
                    hd.getTensp()

                };

                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!" + e.getMessage());
        }
    }

    public void filltableChiTietHoaDon() {
        DefaultTableModel model = (DefaultTableModel) lblhoadonchitiet.getModel();
        model.setRowCount(0);
        try {
            List<HoaDonChiTiet> list = dao1.selectAll();
            for (HoaDonChiTiet hdct : list) {

                Object[] row = {
                    hdct.getMaHDCT(),
                    hdct.getMaSP(),
                    hdct.getThanhTien(),
                    hdct.getMaHD(),};

                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!" + e.getMessage());
        }
    }

    public void filltablesanpham() {
        DefaultTableModel model = (DefaultTableModel) lblsanpham.getModel();
        model.setRowCount(0);
        try {
            String keyword = txttimkiem.getText();
            List<SanPham> list = spdao.selectByKeyword(keyword);
            for (SanPham sp : list) {
                Object[] row = {                 
                    sp.getTenSP(),                                   
                    sp.getGia()
                };

                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!" + e.getMessage());
        }
    }

    void insert() {
        if (validates()) {
            String mahd = txtmaHD.getText();
            HoaDon hd = dao.selectById(mahd);
            
            try {
                hd = getform();
                dao.insert(hd); // Thêm mới
                tinhtongtien();
                this.clearForm(); // Xóa trắng form
                showNewData(hd);
                showNewDatavuathem(hd);
                MsgBox.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm mới thất bại!"+e.getMessage());
            }
        }
    }

//    void showNewData(HoaDon hd) {
//        DefaultTableModel model = (DefaultTableModel) lblhoadon.getModel();
//        model.setRowCount(0); // Xóa hết các hàng trong bảng
//
//        Object[] rowData = new Object[model.getColumnCount()];
//
//        rowData[0] = hd.getTensp();
//        rowData[1] = hd.getMaKH();
//        rowData[2] = hd.getNgayLap();
//        rowData[3] = hd.getDongia();
//        rowData[4] = hd.getSoluong();
//        double tongTien = hd.getSoluong() * hd.getDongia();
//        rowData[5] = tongTien;
//        model.addRow(rowData); // Thêm hàng mới vào bảng
//
//        // Cuộn xuống hàng đầu tiên trong bảng
//        lblhoadon.scrollRectToVisible(lblhoadon.getCellRect(0, 0, true));
//        // Chọn hàng đầu tiên
//        lblhoadon.setRowSelectionInterval(0, 0);
//    }
int currentRow = 0; // Biến để theo dõi hàng tiếp theo để thêm vào bảng

//void showNewData(HoaDon hd) {
//    DefaultTableModel model = (DefaultTableModel) lblhoadon.getModel();
//
//    Object[] rowData = new Object[model.getColumnCount()];
//
//    rowData[0] = hd.getTensp();
//    rowData[1] = hd.getMaKH();
//    rowData[2] = hd.getNgayLap();
//    rowData[3] = hd.getDongia();
//    rowData[4] = hd.getSoluong();
//    double tongTien = hd.getSoluong() * hd.getDongia();
//    rowData[5] = tongTien;
//
//    // Kiểm tra xem có đủ hàng để chứa sản phẩm mới hay không
//    if (currentRow < model.getRowCount()) {
//        model.removeRow(currentRow); // Xóa hàng tiếp theo
//        model.insertRow(currentRow, rowData); // Thêm hàng mới vào hàng tiếp theo
//    } else {
//        model.addRow(rowData); // Thêm hàng mới vào cuối bảng
//    }
//
//    currentRow++; // Tăng biến currentRow để chuẩn bị cho sản phẩm tiếp theo
//
//    // Cuộn xuống hàng cuối cùng trong bảng
//    lblhoadon.scrollRectToVisible(lblhoadon.getCellRect(model.getRowCount() - 1, 0, true));
//    // Chọn hàng cuối cùng
//    lblhoadon.setRowSelectionInterval(model.getRowCount() - 1, model.getRowCount() - 1);
//    double total = 0;
//    for (int row = 0; row < model.getRowCount(); row++) {
//        double rowTotal = (double) model.getValueAt(row, 5);
//        total += rowTotal;
//         txttongtienn.setText(String.valueOf(total));
//}
void showNewData(HoaDon hd) {
    DefaultTableModel model = (DefaultTableModel) lblhoadon.getModel();
   Object[] rowData = new Object[model.getColumnCount()];
     rowData[0] = hd.getTensp();
    rowData[1] = hd.getMaKH();
    rowData[2] = hd.getNgayLap();
    rowData[3] = hd.getDongia();
    rowData[4] = hd.getSoluong();
    double tongTien = hd.getSoluong() * hd.getDongia();
    rowData[5] = tongTien;

    model.addRow(rowData); // Thêm hàng mới vào bảng

    // Tính toán tổng tiền
    double total = 0;
    for (int row = 0; row < model.getRowCount(); row++) {
        double rowTotal = (double) model.getValueAt(row, 5);
        total += rowTotal;
    }

    // Hiển thị tổng tiền trên JTextField
    txttongtienn.setText(String.valueOf(total));

    // Cuộn xuống hàng đầu tiên trong bảng
    lblhoadon.scrollRectToVisible(lblhoadon.getCellRect(0, 0, true));
    // Chọn hàng đầu tiên
    lblhoadon.setRowSelectionInterval(0, 0);
}
    void showNewDatavuathem(HoaDon hd) {
        DefaultTableModel model = (DefaultTableModel) lblhoadon1.getModel();
        Object[] rowData = new Object[model.getColumnCount()];
        rowData[0] = hd.getMaHD();
        rowData[1] = hd.getMaNV();
        rowData[2] = hd.getMaKH();
        rowData[3] = hd.getNgayLap();
        rowData[4] = hd.getDongia();
        rowData[5] = hd.getSoluong();
        double tongTien = hd.getSoluong() * hd.getDongia();
        rowData[6] = tongTien;
        rowData[7] = hd.getTensp();

        model.insertRow(0, rowData); // Chèn hàng mới vào vị trí đầu tiên của bảng

        // Cuộn xuống hàng đầu tiên trong bảng
        lblhoadon1.scrollRectToVisible(lblhoadon1.getCellRect(0, 0, true));
        // Chọn hàng đầu tiên
        lblhoadon1.setRowSelectionInterval(0, 0);
    }

    void insert1() {

        String mahdct = txtmahdct.getText();
        HoaDonChiTiet model = dao1.selectById(mahdct);

        if (model != null) {
            MsgBox.alert(this, "Mã chuyên đề đã tồn tại");
        } else {
            model = getForm1();

            try {
                dao1.insert(model); // Thêm mới
                this.filltableChiTietHoaDon(); // Đổ lại bảng
                this.clearForm1(); // Xóa trắng form
                MsgBox.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm mới thất bại!" + e.getMessage());
            }
        }
    }

    void update() {

        HoaDon hd = this.getform();
        try {
            dao.update(hd); // Cập nhật
            this.filltableHoaDon();// Đổ lại bảng
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!" + e.getMessage());
        }

    }

    void update1() {
        if (validateshdct()) {
            HoaDonChiTiet hdct = this.getForm1();

            try {
                dao1.update(hdct); // Cập nhật
                this.filltableChiTietHoaDon();// Đổ lại bảng
                MsgBox.alert(this, "Cập nhật thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại!");
            }
        }
    }

    void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa !");
        } else if (MsgBox.confirm(this, "Bạn thực sự muốn xóa người này?")) {
            String maHD = txtmaHD.getText();
            try {
                dao.delete(maHD);
                this.filltableHoaDon();
                this.clearForm();
                MsgBox.alert(this, "Xóa thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại!");
            }
        }
    }

    void delete1() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa người học!");
        } else if (MsgBox.confirm(this, "Bạn thực sự muốn xóa người học này?")) {
            String MaHDCT = txtmahdct.getText();
            try {
                dao1.delete(MaHDCT);
                this.filltableChiTietHoaDon();
                this.clearForm1();
                MsgBox.alert(this, "Xóa thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại!");
            }
        }
    }

    void clearForm() {
//        HoaDon hd = new HoaDon();
//        //this.setform(hd);
//        //this.filltableHoaDon();
//        //showNewData(hd);
        this.row = -1;
        this.updateStatus();
        DefaultTableModel model = (DefaultTableModel) lblhoadon.getModel();
        model.setRowCount(0);
    }

    void clearForm1() {
        HoaDonChiTiet hdct = new HoaDonChiTiet();
        this.setForm1(hdct);
        this.row = -1;
        this.updateStatus1();
    }

    void edit() {
        String maHD = (String) lblhoadon.getValueAt(this.row, 0);
        HoaDon hd = dao.selectById(maHD);
        this.row = -1;
        this.setform(hd);
        this.updateStatus();

    }

    void edit1() {
        String MaHDCT = (String) lblhoadonchitiet.getValueAt(this.row, 0);
        HoaDonChiTiet hdct = dao1.selectById(MaHDCT);

        this.setForm1(hdct);
        this.updateStatus1();

    }

    void setform(HoaDon hd) {
        txtmaHD.setText(hd.getMaHD());
        txtMaKh.setText(hd.getMaKH());
        datengaylap.setDate(hd.getNgayLap());
        txtdongia1.setText(String.valueOf(hd.getDongia()));
        txtsoluong1.setText(String.valueOf(hd.getSoluong()));
        txttongtienn.setText(String.valueOf(hd.getTongTien()));
        txttensp.setText(hd.getTensp());

    }

    HoaDon getform() {
        HoaDon hd = new HoaDon();
        hd.setMaHD(txtmaHD.getText());
        hd.setMaKH(txtMaKh.getText());
        hd.setNgayLap(datengaylap.getDate());
        hd.setDongia(Float.parseFloat(txtdongia1.getText()));
        hd.setSoluong(Integer.parseInt(txtsoluong1.getText()));
        hd.setTongTien(Float.parseFloat(txttongtienn.getText()));
        hd.setTensp(txttensp.getText());

        hd.setMaNV(txtmaNV.getText());

        return hd;
    }

    void setForm1(HoaDonChiTiet hdct) {
        txtmahdct.setText(hdct.getMaHDCT());
        txtMaHD1.setText(hdct.getMaHD());
        txtmasp.setText(hdct.getMaSP());
        txtthanhtien.setText(String.valueOf(hdct.getThanhTien()));
    }

    HoaDonChiTiet getForm1() {
        HoaDonChiTiet hdct = new HoaDonChiTiet();
        hdct.setMaHDCT(txtmahdct.getText());
        hdct.setMaSP(txtmasp.getText());
        hdct.setMaHD(txtMaHD1.getText());
        hdct.setThanhTien(Double.parseDouble(txtthanhtien.getText()));

        return hdct;

    }

    void first() {
        this.row = 0;
        this.edit1();
    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit1();
        }
    }

    void next() {
        if (this.row < lblhoadon.getRowCount() - 1) {
            this.row++;
            this.edit1();
        }
    }

    void last() {
        this.row = lblhoadon.getRowCount() - 1;
        this.edit1();
    }

    void first1() {
        this.row = 0;
        this.edit1();
    }

    void prev1() {
        if (this.row > 0) {
            this.row--;
            this.edit1();
        }
    }

    void next1() {
        if (this.row < lblhoadonchitiet.getRowCount() - 1) {
            this.row++;
            this.edit1();
        }
    }

    void last1() {
        this.row = lblhoadonchitiet.getRowCount() - 1;
        this.edit1();
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == lblhoadon.getRowCount() - 1);
        // Trạng thái form
        txtmaHD.setEditable(!edit);
        btnThem2.setEnabled(!edit);
        btnSua2.setEnabled(edit);
        btnXoa2.setEnabled(edit);

        // Trạng thái điều hướng
        btnbrep.setEnabled(edit && !first);
        btnFirst.setEnabled(edit && !first);
        btnLast.setEnabled(edit && !last);
        btnNext.setEnabled(edit && !last);
    }

    void updateStatus1() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == lblhoadonchitiet.getRowCount() - 1);
        // Trạng thái form
        txtmahdct.setEditable(!edit);
        btnThem2.setEnabled(!edit);
        btnSua2.setEnabled(edit);
        btnXoa2.setEnabled(edit);

        // Trạng thái điều hướng
        btnbrep.setEnabled(edit && !first);
        btnFirst.setEnabled(edit && !first);
        btnLast.setEnabled(edit && !last);
        btnNext.setEnabled(edit && !last);
    }

    private void timKiem() {
        this.filltablesanpham();
        this.clearForm();
        this.row = -1;
        this.updateStatus();

    }

    public boolean validates() {
        if (txtmaHD.getText().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập mã hóa đơn");
            txtmaHD.requestFocus();
            return false;
        }

        if (txtMaKh.getText().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập mã khách hàng");
            txtMaKh.requestFocus();
            return false;
        }

        if (txtmaNV.getText().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập mã nhân viên");
            txtmaNV.requestFocus();
            return false;
        }
        if (datengaylap.getDate() == null) {
            MsgBox.alert(this, "Chưa chọn ngày lập");
            datengaylap.requestFocus();
            return false;
        }
        return true;

    }

    public boolean validateshdct() {
        if (txtmahdct.getText().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập mã hóa đơn chi tiết");
            txtmahdct.requestFocus();
            return false;
        }
        if (txtmaHD.getText().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập mã hóa đơn");
            txtmaHD.requestFocus();
            return false;
        }

        if (txtmasp.getText().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập mã sản phẩm");
            txtmasp.requestFocus();
            return false;
        }

//        if (txtten.getText().isEmpty()) {
//            MsgBox.alert(this, "Chưa nhập tên sản phẩm");
//            txtten.requestFocus();
//            return false;
//        }
//        if (txtdongia.getText().isEmpty()) {
//            MsgBox.alert(this, "Chưa nhập đơn giá");
//            txtten.requestFocus();
//            return false;
//        }
//        if (txtsoluong.getText().isEmpty()) {
//            MsgBox.alert(this, "Chưa nhập số lượng");
//            txtten.requestFocus();
//            return false;
//        }
//        if (txtgiamgia.getText().isEmpty()) {
//            MsgBox.alert(this, "Chưa nhập giảm giá ");
//            txtten.requestFocus();
//            return false;
//        }
//        if (txtthanhtien.getText().isEmpty()) {
//            MsgBox.alert(this, "chưa nhập tổng tiền");
//            txtten.requestFocus();
//            return false;
//        }
        return true;

    }

    public void timtiem() {
        this.filltablesanpham();
        this.clearForm();
        this.row = -1;
        this.updateStatus();
    }

    public static void showMyJDialog() {
        JFrame parentFrame = new JFrame(); // Thay thế parentFrame bằng JFrame thực tế của bạn
        LichSuhd dialog = new LichSuhd(parentFrame, true);
        dialog.setVisible(true);
    }

   public void tinhtongtien(){
       double sum=0.0;
       for (SanPham sp  : listsp) {
           sum += sp.getGia() ;
       }
        DecimalFormat decimalFormat = new DecimalFormat("#.##");
        String formattedTotalAmount = decimalFormat.format(sum);
        txttongtienn.setText(formattedTotalAmount);
   }
}
