/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Com.Sport.TroGiup;

import Com.Sport.Dao.NhanVienDao;
import Com.Sport.Entity.NhanVien;
import Com.Sport.ultils.Auth;
import Com.Sport.ultils.MsgBox;
import Com.Sport.ultils.XImage;
import Com.Sport.TroGiup.QuenJDialog;
import java.awt.Color;
import java.awt.Font;

import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import javax.swing.JTextField;
/**
 *
 * @author ADMIN
 */
public class DangNhap extends javax.swing.JDialog {

    NhanVienDao dao = new NhanVienDao();

    /**
     * Creates new form DangNhap
     */
    public DangNhap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("ĐĂNG NHẬP QUẢN LÝ SHOP THỂ THAO");
        initComponents();
        init();
         removetext(txtMatKhau);
        addtext(txtMaNV);
        addtext(txtMatKhau);
        removetext(txtMaNV);
        txtMatKhau.requestFocus();
        txtMaNV.requestFocus();
       
       
    }
    public void addtext(JTextField textfield){
        Font font = textfield.getFont();
        font = font.deriveFont(Font.ITALIC);
        textfield.setFont(font);
        textfield.setForeground(Color.gray);
    }
 public void removetext(JTextField textfield){
        Font font = textfield.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textfield.setFont(font);
        textfield.setForeground(Color.black);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDangNhap = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        chkhienthi = new javax.swing.JCheckBox();
        txtMatKhau = new javax.swing.JPasswordField();
        txtMaNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jblquenpass = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/Sport/Icon/Open lock.png"))); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, 40));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/Sport/Icon/Exit.png"))); // NOI18N
        btnExit.setText("Kết thúc");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 100, 40));

        chkhienthi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkhienthi.setText("Hiển thị mật khẩu?");
        chkhienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkhienthiActionPerformed(evt);
            }
        });
        getContentPane().add(chkhienthi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        txtMatKhau.setText("123");
        txtMatKhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMatKhauFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatKhauFocusLost(evt);
            }
        });
        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyPressed(evt);
            }
        });
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 300, -1));

        txtMaNV.setText("NamVP");
        txtMaNV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaNVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaNVFocusLost(evt);
            }
        });
        getContentPane().add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 300, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên đăng nhập");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mật khẩu");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, -1));

        jblquenpass.setBackground(new java.awt.Color(255, 255, 255));
        jblquenpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblquenpass.setForeground(new java.awt.Color(255, 255, 255));
        jblquenpass.setText("Quên Mật Khẩu?");
        jblquenpass.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jblquenpassAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jblquenpassAncestorRemoved(evt);
            }
        });
        jblquenpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblquenpassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblquenpassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblquenpassMouseExited(evt);
            }
        });
        getContentPane().add(jblquenpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/Sport/logos/bground.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dangNhap();
        }
    }//GEN-LAST:event_txtMatKhauKeyPressed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        this.dangNhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        ketthuc();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtMaNVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaNVFocusGained
       if(txtMaNV.getText().equals("Username")){
           txtMaNV.setText(null);
           txtMaNV.requestFocus();
           removetext(txtMaNV);
       }
    }//GEN-LAST:event_txtMaNVFocusGained

    private void txtMatKhauFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatKhauFocusGained
        if(txtMatKhau.getText().equals("Password")){
            txtMatKhau.setText(null);
            txtMatKhau.requestFocus();
            txtMatKhau.setEchoChar('@');
            removetext(txtMatKhau);
        }
    }//GEN-LAST:event_txtMatKhauFocusGained

    private void txtMaNVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaNVFocusLost
        if (txtMaNV.getText().length()==0) {
            addtext(txtMaNV);
            txtMaNV.setText("Username");
        }
    }//GEN-LAST:event_txtMaNVFocusLost

    private void txtMatKhauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatKhauFocusLost
        if (txtMatKhau.getText().length()==0) {
            addtext(txtMatKhau);
            txtMatKhau.setText("Password");
            txtMatKhau.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtMatKhauFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void chkhienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkhienthiActionPerformed
        Hienthipass();
    }//GEN-LAST:event_chkhienthiActionPerformed

    private void jblquenpassAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jblquenpassAncestorMoved
        
    }//GEN-LAST:event_jblquenpassAncestorMoved

    private void jblquenpassAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jblquenpassAncestorRemoved
        
    }//GEN-LAST:event_jblquenpassAncestorRemoved

    private void jblquenpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblquenpassMouseEntered
        jblquenpass.setForeground(Color.red);
    }//GEN-LAST:event_jblquenpassMouseEntered

    private void jblquenpassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblquenpassMouseExited
        jblquenpass.setForeground(Color.white);
    }//GEN-LAST:event_jblquenpassMouseExited

    private void jblquenpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblquenpassMouseClicked
        // TODO add your handling code here:
        this.dispose();
        quenMatKhau();
    }//GEN-LAST:event_jblquenpassMouseClicked
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhap dialog = new DangNhap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnExit;
    private javax.swing.JCheckBox chkhienthi;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jblquenpass;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
 public static final Logger logger = Logger.getLogger(DangNhap.class);

    private void init() {
       PropertyConfigurator.configure("\\DuAn1\\src\\Com\\Sport\\Log\\log4jj.properties");
        setIconImage(XImage.getAppIcon());
        //setSize(1000, 600);
        setLocationRelativeTo(null);
        Color yellowColor = Color.YELLOW;
        Border yellowBorder = BorderFactory.createLineBorder(yellowColor);
    }
    NhanVienDao nhanvien = new NhanVienDao();

    void dangNhap() {
        String manv = txtMaNV.getText();
        String matKhau = new String(txtMatKhau.getPassword());
        NhanVien nhanVien = dao.selectById(manv);
        if(manv.isEmpty()){
            MsgBox.alert(this, "Bạn chưa nhập tên đăng nhập");
        } else if (nhanVien == null) {
            MsgBox.alert(this, "Sai tên đăng nhập");
        } else if(!matKhau.equals(nhanVien.getMatKhau())){
           // logger.warn(" Người dùng nhập đúng tên đăng nhập "+manv +" nhưng sai mật khẩu!");
            MsgBox.alert(this, "Sai mật khẩu!");
             logger.warn(" Người dùng nhập đúng tên đăng nhập "+manv +" nhưng sai mật khẩu!");
        }else{
            if(matKhau.isEmpty()){
                MsgBox.alert(this, "Bạn chưa nhập mât khẩu");
            }else if (!nhanVien.getMatKhau().equals(matKhau)) {
                MsgBox.alert(this, "Sai mật khẩu");
            } else {
                Auth.user = nhanVien;
                this.dispose();
            }
        }
    }

    private void Hienthipass() {
        if (chkhienthi.isSelected()) {
            txtMatKhau.setEchoChar((char) 0); // Hiển thị mật khẩu
        } else {
            txtMatKhau.setEchoChar('\u2022'); // Ẩn mật khẩu
        }
    }

    private void ketthuc() {

        if (MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng?")) {
            System.exit(0);
        }
    }
    public void quenMatKhau() {
        QuenJDialog mk = new QuenJDialog(null, true);
        mk.setVisible(true);
    }

}
